//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPage.Page_WCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InQuerykisokBuy", Namespace="http://schemas.datacontract.org/2004/07/PageWcfService")]
    [System.SerializableAttribute()]
    public partial class InQuerykisokBuy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kisokBuyNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nextpageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rowField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kisokBuyNum {
            get {
                return this.kisokBuyNumField;
            }
            set {
                if ((object.ReferenceEquals(this.kisokBuyNumField, value) != true)) {
                    this.kisokBuyNumField = value;
                    this.RaisePropertyChanged("kisokBuyNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nextpage {
            get {
                return this.nextpageField;
            }
            set {
                if ((this.nextpageField.Equals(value) != true)) {
                    this.nextpageField = value;
                    this.RaisePropertyChanged("nextpage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int row {
            get {
                return this.rowField;
            }
            set {
                if ((this.rowField.Equals(value) != true)) {
                    this.rowField = value;
                    this.RaisePropertyChanged("row");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnResult", Namespace="http://schemas.datacontract.org/2004/07/PageWcfService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebAppPage.Page_WCF.QuerykisokBuy))]
    public partial class ReturnResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogSnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnMsgNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogSn {
            get {
                return this.LogSnField;
            }
            set {
                if ((this.LogSnField.Equals(value) != true)) {
                    this.LogSnField = value;
                    this.RaisePropertyChanged("LogSn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMsg {
            get {
                return this.ReturnMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMsgField, value) != true)) {
                    this.ReturnMsgField = value;
                    this.RaisePropertyChanged("ReturnMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnMsgNo {
            get {
                return this.ReturnMsgNoField;
            }
            set {
                if ((this.ReturnMsgNoField.Equals(value) != true)) {
                    this.ReturnMsgNoField = value;
                    this.RaisePropertyChanged("ReturnMsgNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuerykisokBuy", Namespace="http://schemas.datacontract.org/2004/07/PageWcfService")]
    [System.SerializableAttribute()]
    public partial class QuerykisokBuy : WebAppPage.Page_WCF.ReturnResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebAppPage.Page_WCF.kisokDataQuery[] kisokDataQueryListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nowpageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebAppPage.Page_WCF.kisokDataQuery[] kisokDataQueryList {
            get {
                return this.kisokDataQueryListField;
            }
            set {
                if ((object.ReferenceEquals(this.kisokDataQueryListField, value) != true)) {
                    this.kisokDataQueryListField = value;
                    this.RaisePropertyChanged("kisokDataQueryList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nowpage {
            get {
                return this.nowpageField;
            }
            set {
                if ((this.nowpageField.Equals(value) != true)) {
                    this.nowpageField = value;
                    this.RaisePropertyChanged("nowpage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="kisokDataQuery", Namespace="http://schemas.datacontract.org/2004/07/PageWcfService")]
    [System.SerializableAttribute()]
    public partial class kisokDataQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyPhoneNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyAmount {
            get {
                return this.BuyAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyAmountField, value) != true)) {
                    this.BuyAmountField = value;
                    this.RaisePropertyChanged("BuyAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyCount {
            get {
                return this.BuyCountField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyCountField, value) != true)) {
                    this.BuyCountField = value;
                    this.RaisePropertyChanged("BuyCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyNum {
            get {
                return this.BuyNumField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyNumField, value) != true)) {
                    this.BuyNumField = value;
                    this.RaisePropertyChanged("BuyNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuyPhoneNum {
            get {
                return this.BuyPhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyPhoneNumField, value) != true)) {
                    this.BuyPhoneNumField = value;
                    this.RaisePropertyChanged("BuyPhoneNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Page_WCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TESTData", ReplyAction="http://tempuri.org/IService1/TESTDataResponse")]
        WebAppPage.Page_WCF.QuerykisokBuy TESTData(WebAppPage.Page_WCF.InQuerykisokBuy Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TESTData", ReplyAction="http://tempuri.org/IService1/TESTDataResponse")]
        System.Threading.Tasks.Task<WebAppPage.Page_WCF.QuerykisokBuy> TESTDataAsync(WebAppPage.Page_WCF.InQuerykisokBuy Input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebAppPage.Page_WCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebAppPage.Page_WCF.IService1>, WebAppPage.Page_WCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAppPage.Page_WCF.QuerykisokBuy TESTData(WebAppPage.Page_WCF.InQuerykisokBuy Input) {
            return base.Channel.TESTData(Input);
        }
        
        public System.Threading.Tasks.Task<WebAppPage.Page_WCF.QuerykisokBuy> TESTDataAsync(WebAppPage.Page_WCF.InQuerykisokBuy Input) {
            return base.Channel.TESTDataAsync(Input);
        }
    }
}
